version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200525
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-20200525
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  java-solution:
    build: .
    volumes:
      - .:/test
    depends_on:
      - chrome
    links:
      - selenium-hub
    environment:
      - USE_DOCKER_SELENIUM=true
      